[#299] Public actions view
fiqus/coobs pull request #311
Opened 2021-04-06 19:54 UTC by diegomanuel

Issue: https://github.com/fiqus/coobs/issues/299

2021-04-16 14:09 UTC, mjvallone requested changes
sólo miré el código, no lo probé andando

2021-04-16 14:09 UTC, mjvallone commented on api/tests/test_views.py
> +        self.create_action(name="action 2")
le agregaría una acción privada y chequear que devuelva sólo 2 acciones (filtrando la privada)

2021-04-16 14:09 UTC, mjvallone commented on api/views/views.py
> +    #     starting_day_of_current_year = datetime.now().date().replace(month=1, day=1)
se puede borrar el código comentado?

2021-04-16 14:31 UTC, lucasferraro reviewed
Hay un `ActionsRankingView.list` que entiendo era un antigua forma de consultar las acciones publicas, debería volar?

2021-04-16 14:31 UTC, lucasferraro commented on api/views/views.py
> +        action_data = Action.get_public_actions(more, limit)
La forma actual de paginar resultados con el `StandardResultsSetPagination` no sirve para el infinite scroll?

2021-04-19 19:02 UTC, diegomanuel commented on api/tests/test_views.py
> +        self.create_action(name="action 2")
En el caso de ese test, solo verifica que se traigan todas las acciones (públicas+privadas) de la coope actual logueada.
Para probar el nuevo endpoint que solo trae las públicas, creé el nuevo test case `test_retrieve_public_actions_list` que cubre todos los casos!

2021-04-19 19:15 UTC, diegomanuel commented
> Hay un `ActionsRankingView.list` que entiendo era un antigua forma de consultar las acciones publicas, debería volar?

Podría ser, aunque quizá todavía queramos tener/mostrar algún tipo de "ranking" más adelante (y esa view tiene un lindo ejemplito ya armado).
Por ahora la dejé pero le agregué un `@TODO` para dejarla marcada para una posible volada a futuro!

2021-04-19 20:59 UTC, lucasferraro approved these changes

2021-04-19 21:32 UTC, merged